import React, { useState } from "react";
import Head from "next/head";
import AppointmentDetails from "../components/AppointmentDetails";
import Files from "../components/Files";
import Notes from "../components/Notes";
import PatientList from "../components/PatientList";
import ProfileDetails from "../components/ProfileDetails";
import TopNavBar from "../components/TopNavBar";
import LeftPanel from "../components/LeftPanel";

export default function Home({ data, doctor, appointments, files }) {
  console.log(doctor);
  const [leftPanel, setLeftPanel] = useState(false);
  return (
    <div>
      <Head>
        <title>Krishworks Frontend Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-[#f2f5fa]">
        <div>
          {leftPanel ? (
            <LeftPanel
              doctorName={doctor.name}
              doctorType={doctor.specification}
            />
          ) : null}
        </div>

        {leftPanel ? (
          <div
            onClick={() => setLeftPanel(!leftPanel)}
            className="absolute top-5 left-48"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="h-6 w-6"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={2}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M6 18L18 6M6 6l12 12"
              />
            </svg>
          </div>
        ) : null}

        <div>
          <TopNavBar
            name={data.name}
            setLeftPanel={setLeftPanel}
            leftPanel={leftPanel}
          />
          <PatientList name={data.name} />
        </div>

        <div className="grid gap-4 md:grid-cols-3 grid-cols-1 mx-8 ">
          <div className="col-span-2 mt-4">
            <ProfileDetails data={data} />
          </div>

          <Notes doctorName={doctor.name} createdAt={doctor.createdAt} />
          <div className="col-span-2 my-4">
            <AppointmentDetails appointments={appointments} />
          </div>

          <Files files={files} />
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const data = await fetch(
    "https://619f39821ac52a0017ba467e.mockapi.io/patientDetails"
  ).then((res) => res.json());

  const doctor = await fetch(
    "https://619f39821ac52a0017ba467e.mockapi.io/DoctorDetails"
  ).then((res) => res.json());

  const AppointmentDetails = await fetch(
    "https://619f39821ac52a0017ba467e.mockapi.io/appointment_details"
  ).then((res) => res.json());

  const Files = await fetch(
    "https://619f39821ac52a0017ba467e.mockapi.io/Files"
  ).then((res) => res.json());
  return {
    props: {
      data: data[0],
      doctor: doctor[0],
      appointments: AppointmentDetails[0],
      files: Files[0],
    },
  };
}
